language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: cReljg5zXbzOyU3bVH041fL1pR07Cqn8eO4T3t0kAd+sE9vgbk//d3CYeajFYs1t0Mhw4k5HehDsEptWrn1EBAl57syVtHSo7Ez8Op6gxa/Rde0P7+OKlYpcDCkjYAjjpV40X1RT3sNZKkVT81XhpLQpiSS3QnlLeOJ1pnotktOpwLzC262+128/aG/d+c53GrztHDRxm/G3CfUs6WVVC8lt1xATRGpL+nkMBg4alNOtktoo31msGMNLI9a4A8kiYpMdeDDfUUK7JyzykDoAGR1y9ymeFJMCHkz2gW93FBSdRWkeZWieard4k3sVcKYXWylFzk+Pk8I4hqwQfQb6mSzddhMs72txN+m3PQQ/HE8dp7S426tnDRs8TqOEQb+oFDd39Mj5NUJ9tBWbLY6cDthx9izJGPDdsg4I7RRomPjVV7k6hpPeTbrWKkj/cIy5OCmuzO8/3BQ3LTo7Wu6EZbTVdEJhIFbzzdaMRhmoBSRrLAJt0WaZuLnnjyxf5RFezdcyu48AJIcqkT1BPlkYrHmcR+De1dcnuU6EuRMnicw/qja7sMRXcQsh864ZQP7qEpBQvNvzZplPQ8Nh0PxYkrVHFxFEaNMlhbH99uPg/95gU/CFsj+zFseboLzRdN66O2Wu8+lP7im6W9HVYAVx80V5ElKbkyJl7ZSJHs7NoEQ=
  app: shielded-wave-7452	
